# Site settings
title: "Wang Jinsong Blog"
SEOTitle: "王劲松的博客 | Woody Blog"
header-img: "img/home-bg.jpg"
email: "haorenmin2008@163.com"
description: "这里是 @woodywang 的个人博客，与你一起发现更大的世界"
keyword: "博客, 个人网站, 互联网, AI, LLM"
url: "" # your site URL, e.g., "https://woodywang.github.io"
baseurl: "" # e.g., "/blog" if your blog is hosted at "host/blog"

# Publish posts or collection documents with a future date
future: true

# SNS settings
RSS: false
weibo_username: "huxpro"
zhihu_username: "huxpro"
github_username: "huxpro"
twitter_username: "huxpro"
# facebook_username: "huxpro"
# linkedin_username: "firstname-lastname-idxxxx"

# Build settings
highlighter: "rouge" # 'pygments' is no longer supported
permalink: "pretty"
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
anchorjs: true # if you want to customize anchor links, see line 181 of post.html
# timezone: "CN" # Uncomment if you have timezone issues (e.g. #68)

# Plugins
plugins:
  - jekyll-paginate

# Markdown settings
markdown: "kramdown"
kramdown:
  input: "GFM" # use GitHub Flavored Markdown
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: "hux"

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: "your-baidu-id"

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: "huangxuan.me"

# Sidebar settings
sidebar: true # whether or not to use Sidebar
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: "https://github.com/Huxpro.png" # use absolute URL

# Featured Tags
featured-tags: true # whether or not to use Featured Tags
featured-condition-size: 1 # A tag will be featured if its size exceeds this value

# Progressive Web App
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g., post preview)
page-mathjax: false

# Friends
friends:
  - { title: "乱序（Midare）", href: "http://mida.re/" }
  - { title: "Ebn Zhang", href: "https://ebnbin.dev/" }
  - { title: "Kun Qian", href: "http://kunq.me" }
  - { title: "Sherry Woo", href: "https://sherrywoo.me/" }
  - { title: "SmdCn", href: "http://blog.smdcn.net" }
  - { title: "JiyinYiyong", href: "http://tiye.me/" }
  - { title: "DHong Say", href: "http://dhong.co" }
  - { title: "尹峰以为", href: "http://ingf.github.io/" }
